### ISSUE TITLE
App shows logged in, but account modal shows logged out

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#316]
**Describe the bug**
As a user I go to https://app.web3inbox.com/notifications/new-app and I am logged in.
I can see my subscriptions.

When I want to logout I click the account icon, but instead of seeing the account modal I see the connect modal.

**To Reproduce**

- Use MM extension

**Expected behavior**

When logged in, clicking the account icon shows the currently connected account.

**Screenshots**

<img width="1222" alt="Screenshot 2024-01-02 at 11 54 05" src="https://github.com/WalletConnect/web3inbox/assets/116099/e2d81dbc-3ecd-4a69-b3c4-75d842d9f097">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Wallet: Metamask extension

**Comment by chadyj** [comment]
Possibly related: 
@enesozturk reported

> Hey team, investigating an interesting issue on web3modal which we've discovered this in [app.web3inbox.com](http://app.web3inbox.com/). I'm not sure if this is already known:
Opening the app which uses w3m > connecting > opening same app in a new tab* > repeat this
After some time, even though the isConnected is true, it's rendering not connected state and opens 'connect' page when we click the button. This can be reproducible in [web3modal.com](http://web3modal.com/) as well. Same for the ethers lib.
Can you please try it and share your experience? Creating a issue for it, it's a bit annoying, will be focusing it to fix asap

**Comment by chadyj** [comment]
Fixed in the latest web3modal upgrade

**Comment by chadyj** [comment]
Re-opening. This issue still occurs when using MM.

Doesn't seem like it was fixed here https://github.com/WalletConnect/web3inbox/issues/324

cc @enesozturk

**Comment by enesozturk** [comment]
@chadyj Yes, actually it is not expected to fix the MM issue on w3i. That issue is more about w3m - MM related other than w3i. 

Previously I created this issue on w3m: https://github.com/WalletConnect/web3modal/issues/1547. Fixing it on w3m will automatically fix the w3i too. 

So it'll be an investigation since no one has an idea why it's happening and it's hard to reproduce and cannot be reproduced with other wallets. [Slack conv](https://walletconnect.slack.com/archives/C03RVH94K5K/p1701896280693259)

If you get the same error with other wallets, please let me know so it helps to find the reason.
